-- MySQL Script generated by MySQL Workbench
-- Wed Jun 21 15:20:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inovin_db_local
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `roles` ;

CREATE TABLE IF NOT EXISTS `roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colors` ;

CREATE TABLE IF NOT EXISTS `colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terroirs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terroirs` ;

CREATE TABLE IF NOT EXISTS `terroirs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cepages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cepages` ;

CREATE TABLE IF NOT EXISTS `cepages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tastes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tastes` ;

CREATE TABLE IF NOT EXISTS `tastes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tastes and aromas` VARCHAR(45) NOT NULL,
  `colors_id` INT NOT NULL,
  `terroirs_id` INT NOT NULL,
  `cepages_id` INT NOT NULL,
  PRIMARY KEY (`id`, `colors_id`, `terroirs_id`, `cepages_id`),
  INDEX `fk_gout_couleur1_idx` (`colors_id` ASC) VISIBLE,
  INDEX `fk_gout_terroir1_idx` (`terroirs_id` ASC) VISIBLE,
  INDEX `fk_gout_cepage1_idx` (`cepages_id` ASC) VISIBLE,
  CONSTRAINT `fk_gout_couleur1`
    FOREIGN KEY (`colors_id`)
    REFERENCES `colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gout_terroir1`
    FOREIGN KEY (`terroirs_id`)
    REFERENCES `terroirs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gout_cepage1`
    FOREIGN KEY (`cepages_id`)
    REFERENCES `cepages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `years`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `years` ;

CREATE TABLE IF NOT EXISTS `years` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `operators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `operators` ;

CREATE TABLE IF NOT EXISTS `operators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bottle_per_cepage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottle_per_cepage` ;

CREATE TABLE IF NOT EXISTS `bottle_per_cepage` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ref` VARCHAR(45) NOT NULL,
  `cepages_id` INT NOT NULL,
  `terroirs_id` INT NOT NULL,
  `colors_id` INT NOT NULL,
  `years_id` INT NOT NULL,
  `operators_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cepages_id`, `terroirs_id`, `colors_id`),
  INDEX `fk_bouteille par cépage_cepage1_idx` (`cepages_id` ASC) VISIBLE,
  INDEX `fk_bouteille par cépage_terroir1_idx` (`terroirs_id` ASC) VISIBLE,
  INDEX `fk_bouteille par cépage_couleur1_idx` (`colors_id` ASC) VISIBLE,
  INDEX `fk_bouteille par cépage_year1_idx` (`years_id` ASC) VISIBLE,
  INDEX `fk_bouteille par cépage_exploitant1_idx` (`operators_id` ASC) VISIBLE,
  CONSTRAINT `fk_bouteille par cépage_cepage1`
    FOREIGN KEY (`cepages_id`)
    REFERENCES `cepages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bouteille par cépage_terroir1`
    FOREIGN KEY (`terroirs_id`)
    REFERENCES `terroirs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bouteille par cépage_couleur1`
    FOREIGN KEY (`colors_id`)
    REFERENCES `colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bouteille par cépage_year1`
    FOREIGN KEY (`years_id`)
    REFERENCES `years` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bouteille par cépage_exploitant1`
    FOREIGN KEY (`operators_id`)
    REFERENCES `operators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasting_sheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasting_sheet` ;

CREATE TABLE IF NOT EXISTS `tasting_sheet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `cepages` VARCHAR(45) NOT NULL,
  `notes` INT NOT NULL,
  `tasting_result_id` INT NOT NULL,
  `bottle_per_cepage_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tasting_result_id`, `bottle_per_cepage_id`),
  INDEX `fk_fiche d'égustation_bouteille par cépage1_idx` (`bottle_per_cepage_id` ASC) VISIBLE,
  CONSTRAINT `fk_fiche d'égustation_bouteille par cépage1`
    FOREIGN KEY (`bottle_per_cepage_id`)
    REFERENCES `bottle_per_cepage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `name` VARCHAR(55) NOT NULL,
  `age` DATE NOT NULL,
  `mail` VARCHAR(90) NOT NULL,
  `password` VARCHAR(120) NOT NULL,
  `tastes_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  `tasting_sheet_id` INT NOT NULL,
  `tasting_sheet_tasting_result_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tastes_id`, `roles_id`, `tasting_sheet_id`, `tasting_sheet_tasting_result_id`),
  INDEX `fk_user_gout_idx` (`tastes_id` ASC) VISIBLE,
  INDEX `fk_user_admi1_idx` (`roles_id` ASC) VISIBLE,
  INDEX `fk_user_fiche d'égustation1_idx` (`tasting_sheet_id` ASC, `tasting_sheet_tasting_result_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_gout`
    FOREIGN KEY (`tastes_id`)
    REFERENCES `tastes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_admi1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_fiche d'égustation1`
    FOREIGN KEY (`tasting_sheet_id` , `tasting_sheet_tasting_result_id`)
    REFERENCES `tasting_sheet` (`id` , `tasting_result_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bottle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottle` ;

CREATE TABLE IF NOT EXISTS `bottle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `year` DATE NOT NULL,
  `price` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasting_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasting_result` ;

CREATE TABLE IF NOT EXISTS `tasting_result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `notes` INT NOT NULL,
  `workshop_id` INT NOT NULL,
  `tasting_sheet_id` INT NOT NULL,
  `tasting_sheet_rtasting_result_id` INT NOT NULL,
  `tasting_sheet_bottle_per_cepage_id` INT NOT NULL,
  PRIMARY KEY (`id`, `workshop_id`, `tasting_sheet_id`, `tasting_sheet_rtasting_result_id`, `tasting_sheet_bottle_per_cepage_id`),
  INDEX `fk_resultat dégustation_fiche d'égustation1_idx` (`tasting_sheet_id` ASC, `tasting_sheet_rtasting_result_id` ASC, `tasting_sheet_bottle_per_cepage_id` ASC) VISIBLE,
  CONSTRAINT `fk_resultat dégustation_fiche d'égustation1`
    FOREIGN KEY (`tasting_sheet_id` , `tasting_sheet_rtasting_result_id` , `tasting_sheet_bottle_per_cepage_id`)
    REFERENCES `tasting_sheet` (`id` , `tasting_result_id` , `bottle_per_cepage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `selection_for_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `selection_for_user` ;

CREATE TABLE IF NOT EXISTS `selection_for_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `bottle_id` INT NOT NULL,
  PRIMARY KEY (`id`, `bottle_id`),
  INDEX `fk_selection pour user_bouteille1_idx` (`bottle_id` ASC) VISIBLE,
  CONSTRAINT `fk_selection pour user_bouteille1`
    FOREIGN KEY (`bottle_id`)
    REFERENCES `bottle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `workshop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workshop` ;

CREATE TABLE IF NOT EXISTS `workshop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `guide` VARCHAR(200) NOT NULL,
  `dosage` BLOB NOT NULL,
  `selection_for_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `selection_for_user_id`),
  INDEX `fk_atelier créa_selection pour user1_idx` (`selection_for_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_atelier créa_selection pour user1`
    FOREIGN KEY (`selection_for_user_id`)
    REFERENCES `selection_for_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasting_result_has_workshop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasting_result_has_workshop` ;

CREATE TABLE IF NOT EXISTS `tasting_result_has_workshop` (
  `tasting_result_id` INT NOT NULL,
  `tasting_result_workshop_id` INT NOT NULL,
  `workshop_id` INT NOT NULL,
  `selection_for_user_id` INT NOT NULL,
  `selection_for_user_bottle_id` INT NOT NULL,
  PRIMARY KEY (`tasting_result_id`, `tasting_result_workshop_id`, `workshop_id`, `selection_for_user_id`, `selection_for_user_bottle_id`),
  INDEX `fk_resultat dégustation_has_atelier créa_atelier créa1_idx` (`workshop_id` ASC) VISIBLE,
  INDEX `fk_resultat dégustation_has_atelier créa_resultat dégust_idx` (`tasting_result_id` ASC, `tasting_result_workshop_id` ASC) VISIBLE,
  INDEX `fk_resultat dégustation_has_atelier créa_selection pour u_idx` (`selection_for_user_id` ASC, `selection_for_user_bottle_id` ASC) VISIBLE,
  CONSTRAINT `fk_resultat dégustation_has_atelier créa_resultat dégustat1`
    FOREIGN KEY (`tasting_result_id` , `tasting_result_workshop_id`)
    REFERENCES `tasting_result` (`id` , `workshop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultat dégustation_has_atelier créa_atelier créa1`
    FOREIGN KEY (`workshop_id`)
    REFERENCES `workshop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultat dégustation_has_atelier créa_selection pour user1`
    FOREIGN KEY (`selection_for_user_id` , `selection_for_user_bottle_id`)
    REFERENCES `selection_for_user` (`id` , `bottle_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
